#Define Project
substitutions:
  name: halo
  version: "25.3.5.3"
  device_description: ${name} - v${version}.

psram:
  mode: octal
  speed: 120MHz

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

esp32_improv:
  authorizer: none

external_components:
  - source: github://yashmulgaonkar/esphome-components
    components: [axs15231, sy6970]

spi:
  id: lily_spi
  type: quad
  clk_pin: 17
  data_pins:
    - 13
    - 18
    - 21
    - 14

captive_portal:

logger:
  level: DEBUG

globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: temp_unit_changed
    type: bool
    initial_value: "true"
# interval:  

api:

http_request:

i2c:
  - sda: 9
    scl: 48
    id: lily_i2c
  - sda: 15
    scl: 10
    id: touch_i2c

output:
  - platform: ledc
    pin: 1
    id: backlight
  
display:
  - platform: axs15231
    id: lily_display
    spi_id: lily_spi
    dimensions:
      height: 640
      width: 180
    cs_pin: 12
    reset_pin: 16
    rotation: 270
    auto_clear_enabled: false

touchscreen:
  - platform: axs15231
    id: lily_touch
    display: lily_display
    i2c_id: touch_i2c
    interrupt_pin: GPIO11
    transform:
      mirror_x: false
      mirror_y: false
      swap_xy: false
    on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );

web_server:
  port: 80

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%
  - id: my_orange
    red: 100%
    green: 50%
    blue: 0%
  - id: my_teal
    red: 0%
    green: 100%
    blue: 100%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%

time:
  - platform: homeassistant
    id: ha_time

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected    

sensor:
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
  - platform: template
    name: DoThing
    id: my_button
    on_press:
      then:
        - logger.log: Button Pressed
        - http_request.get: https://webhook.site/a39c8ab8-028b-45d6-a666-9ab5d8f08f02
        - logger.log: Webhook requested

light:
  - platform: monochromatic
    output: backlight
    name: "Display Backlight"
    restore_mode: ALWAYS_ON

lvgl:
  displays:
    - lily_display
  touchscreens:
    - lily_touch
  buffer_size: 100%
  default_font: montserrat_48
  pages:            
    - id: main_page
      bg_color: my_black
      scrollbar_mode: "OFF"
      widgets:
        - button:
            x: 10
            y: 10 
            width: 160
            height: 160
            id: btn_id
            checkable: true
            widgets:
              - label:
                  align: center
                  text: "Good"
            on_change:
              then:
                - logger.log: display Pressed
                - http_request.get: https://webhook.site/a39c8ab8-028b-45d6-a666-9ab5d8f08f02
                - logger.log: Webhook requested magic
